# Generated by Django 3.0.14 on 2024-02-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('video camera', 'Video Camera'), ('recorder', 'Recorder'), ('magewell', 'Magewell'), ('cable', 'Cable'), ('router', 'Router'), ('hard disk', 'Hard disk'), ('laptop', 'Laptop'), ('adapter', 'Adapter'), ('battery', 'Battery'), ('projector', 'Projector'), ('tripod', 'Tripod'), ('battery camera', 'Battery camera'), ('router', 'Router'), ('charger', 'Charger'), ('thumbdrive', 'Thumbdrive'), ('battery charger', 'Battery charger'), ('cable', 'Cable')], max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('serial_number', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
