# Generated by Django 3.0.14 on 2024-02-14 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateField()),
                ('date_returned', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name_plural': 'Store'},
        ),
        migrations.AddField(
            model_name='assets',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='description',
            field=models.TextField(default='NaN'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='note',
            field=models.TextField(default='NaN'),
        ),
        migrations.DeleteModel(
            name='Apply',
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Assets'),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
