# Generated by Django 3.0.14 on 2024-02-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20240214_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='quantity',
        ),
    ]
