# Generated by Django 3.0.14 on 2024-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20240216_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='date_borrowed',
            field=models.DateField(auto_now=True),
        ),
    ]
