# Generated by Django 3.0.14 on 2024-02-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20240216_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
