# Generated by Django 3.0.14 on 2024-02-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20240217_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='date_added',
            field=models.DateField(),
        ),
    ]
