# Generated by Django 4.2.10 on 2024-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_auto_20240217_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Registration Number"
            ),
        ),
    ]
